# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: "^(htop|vim)/"
      - id: trailing-whitespace
        exclude: "^(htop|vim)/"

  - repo: local
    hooks:
      - id: pre-commit-validate-config
        name: validate pre-commit config
        files: "^.pre-commit-config.yaml$"
        types: [yaml]
        entry: pre-commit validate-config
        language: system
        fail_fast: true

      - id: shellcheck
        name: shellcheck
        types: [shell]
        entry: shellcheck --check-sourced
        language: system
