#!/bin/bash
set -eu

# setup

cd "$(dirname "${BASH_SOURCE[0]}")"
# all paths are relative to $src (repo root), but absolute for ln
src="$(pwd)"
config_items=(
    zsh-completion
)
dot_items=(
    bash_profile
    bashrc
    gitconfig
    gitignore
    gvimrc
    inputrc
    rtorrent.rc
    vim
    vimrc
    xbindkeysrc
    zshenv
    zshrc
)
ln_flags=(
    --force
    --no-dereference
    --relative
    --symbolic
    --verbose
)
pdm_completion_path="$src/zsh-completion/_pdm"

link() { ln "${ln_flags[@]}" "$@" ; }
link_config() { link -- "$src/$1" ~/.config/"$1" ; }
link_dot() { link -- "$src/$1" ~/".$1" ; }
log() { echo "$@" >&2 ; }

mkdir -p ~/bin

echo "- link configs" >&2
for item in "${config_items[@]}" ; do
    link_config "$item"
done
for item in "${dot_items[@]}" ; do
    link_dot "$item"
done

log -n "- pdm zsh completion: "
if [[ -f "$pdm_completion_path" ]] ; then
    log "exists"
elif ! pdm --version &>/dev/null ; then
    log "pdm not installed"
else
    log "creating"
    pdm completion zsh >"$src/zsh-completion/_pdm"
fi

echo "- vscodium"
mkdir -p ~/.config/VSCodium/User
for path in "$src"/VSCodium/User/* ; do
    relative="$(realpath --relative-base="$src" -- "$path")"
    link_config "$relative"
done
