#!/bin/bash
set -eu

# setup

cd "$(dirname "${BASH_SOURCE[0]}")"
# all paths are relative to $src (repo root), but absolute for ln
src="$(pwd)"
config_items=(
    zsh-completion
)
dot_items=(
    bash_profile
    bashrc
    gitconfig
    gitignore
    gvimrc
    inputrc
    rtorrent.rc
    vim
    vimrc
    xbindkeysrc
    zshenv
    zshrc
)

log() {
    echo "$@" >&2
}

link() {
    local flags=(
        --force
        --no-dereference
        --relative
        --symbolic
        "$@"
    )
    ln "${flags[@]}"
}

pdm_zsh_completion() {
    local log_prefix="- python pdm zsh completion: "
    local path="$src/zsh-completion/_pdm"
    if [[ -f "$path" ]] ; then
        log "$log_prefix $path exists"
    elif ! pdm --version &>/dev/null ; then
        log "$log_prefix pdm is not installed"
    else
        log "$log_prefix $path not found, creating"
        pdm completion zsh >"$path"
    fi
}


# main

mkdir -p -- ~/bin ~/.config/pip

log "- link configs"
for item in "${config_items[@]}" ; do
    link -- "$src/$item" ~/.config/"$item"
done
for item in "${dot_items[@]}" ; do
    link -- "$src/$item" ~/."$item"
done
item=pip.conf ; link -- "$src/$item" ~/.config/pip/"$item"

pdm_zsh_completion

log "- vscodium"
mkdir -p -- ~/.config/VSCodium/User
for item in VSCodium/User/* ; do
    link -- "$src/$item" ~/.config/"$item"
done
